### ISSUE TITLE
Residual equal to zero leads to NaN in output of trained model.

### ISSUE THREAD

**Issue by gmmarconi** [enry12/FALKON#1]
Hi, I tried running your implementation of Falkon but I get an error during traning. for a binary classification problem.

Specifically, when computing the conjugate gradient [at line 65](https://github.com/enry12/FALKON/blob/df94589ed15725518d32fe264b6766fa726a3faa/falkon.py#L65), the residual `b` is a vector of zeros, this causes a division by 0 [here](https://github.com/enry12/FALKON/blob/df94589ed15725518d32fe264b6766fa726a3faa/falkon.py#L197).
However, the first residual `b` is computed at [line 61](https://github.com/enry12/FALKON/blob/df94589ed15725518d32fe264b6766fa726a3faa/falkon.py#L61) and shouldn't be zero. 
This results in training a model that outputs `NaN` values.

Am I missing? Any kind of preprocessing on the data or any kind of flag? I tried both gpu and cpu version getting the same error.

**Comment by enricivi** [comment]
Hi @gmmarconi,

Probably your problem is due to some preprocessing issues.

I have uploaded a small dataset (moons_3m_s04.npy), and following the README you can test FALKON's implementation. Actually, you can test the semi-supervised one but the core of this version is always FALKON. 

Let me know if you have some problems to run this test.

Best regards,
@enry12

NB I will finish the README asap
